Repository camaragon/rancid-tomatillos, pull requests merged in 2021-02, with the labels that each got.

#13 Cma/feature/display movies
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/component/App.js
  src/component/App.test.js
  src/component/Movies.js
  src/component/Poster.js
  src/index.js
  src/movieData.js
  src/scss/App.scss
  src/scss/Movies.scss
  src/scss/Poster.scss
  src/scss/index.scss
Labels: enhancement

#14 Ch/feature/conditional rendering
  src/component/App.js
  src/component/MovieInfo.js
  src/component/Movies.js
  src/component/Poster.js
  src/movieData.js
  src/scss/MovieInfo.scss
Labels: enhancement

#17 Cma/feature/network requests async
  src/component/App.js
  src/component/MovieInfo.js
  src/component/Movies.js
  src/component/Poster.js
  src/movieData.js
Labels: enhancement

#18 Ch/feature/scss/single movie view
  src/component/MovieInfo.js
  src/scss/App.scss
  src/scss/MovieInfo.scss
Labels: enhancement

#20 Cma/feature/dashboard styling
  src/component/Poster.js
  src/scss/App.scss
  src/scss/MovieInfo.scss
  src/scss/Movies.scss
  src/scss/Poster.scss
  src/scss/_variables.scss
  src/scss/index.scss
Labels: enhancement

#22 Cma/feature/implement router
  package-lock.json
  package.json
  src/component/App.js
  src/component/MovieInfo.js
  src/component/Movies.js
  src/component/Poster.js
  src/index.js
Labels: enhancement

#24 Cma/feature/search filter sort movies
  package-lock.json
  package.json
  src/component/App.js
  src/component/Form.js
  src/component/MovieInfo.js
  src/component/Movies.js
  src/scss/App.scss
  src/scss/Form.scss
  src/scss/MovieInfo.scss
  src/scss/Poster.scss
Labels: enhancement

#26 Feature/polish sass
  public/index.html
  src/Tomato.js
  src/component/App.js
  src/component/Form.js
  src/component/MovieInfo.js
  src/component/Poster.js
  src/scss/App.scss
  src/scss/Form.scss
  src/scss/MovieInfo.scss
  src/scss/Movies.scss
  src/scss/Poster.scss
  src/scss/_extends.scss
  src/scss/_variables.scss
  src/scss/index.scss
Labels: enhancement

#27 Cma/feature/responsiveness accessibility
  src/component/Form.js
  src/scss/Form.scss
  src/scss/MovieInfo.scss
  src/scss/Poster.scss
  src/scss/index.scss
Labels: enhancement

#28 Cma/feature/update cypress
  cypress/integration/cypress/integration/examples/actions.spec.js
  cypress/integration/cypress/integration/examples/aliasing.spec.js
  cypress/integration/cypress/integration/examples/assertions.spec.js
  cypress/integration/cypress/integration/examples/connectors.spec.js
  cypress/integration/cypress/integration/examples/cookies.spec.js
  cypress/integration/cypress/integration/examples/cypress_api.spec.js
  cypress/integration/cypress/integration/examples/files.spec.js
  cypress/integration/cypress/integration/examples/local_storage.spec.js
  cypress/integration/cypress/integration/examples/location.spec.js
  cypress/integration/cypress/integration/examples/misc.spec.js
  cypress/integration/cypress/integration/examples/navigation.spec.js
  cypress/integration/cypress/integration/examples/network_requests.spec.js
  cypress/integration/cypress/integration/examples/querying.spec.js
  cypress/integration/cypress/integration/examples/spies_stubs_clocks.spec.js
  cypress/integration/cypress/integration/examples/traversal.spec.js
  cypress/integration/cypress/integration/examples/utilities.spec.js
  cypress/integration/cypress/integration/examples/viewport.spec.js
  cypress/integration/cypress/integration/examples/waiting.spec.js
  cypress/integration/cypress/integration/examples/window.spec.js
  cypress/integration/examples/actions.spec.js
  cypress/integration/examples/aliasing.spec.js
  cypress/integration/examples/assertions.spec.js
  cypress/integration/examples/connectors.spec.js
  cypress/integration/examples/cookies.spec.js
  cypress/integration/examples/cypress_api.spec.js
  cypress/integration/examples/files.spec.js
  cypress/integration/examples/local_storage.spec.js
  cypress/integration/examples/location.spec.js
  cypress/integration/examples/misc.spec.js
  cypress/integration/examples/navigation.spec.js
  cypress/integration/examples/network_requests.spec.js
  cypress/integration/examples/querying.spec.js
  cypress/integration/examples/spies_stubs_clocks.spec.js
  cypress/integration/examples/traversal.spec.js
  cypress/integration/examples/utilities.spec.js
  cypress/integration/examples/viewport.spec.js
  cypress/integration/examples/waiting.spec.js
  cypress/integration/examples/window.spec.js
  cypress/integration/movie_display.spec.js
  cypress/integration/movie_info.spec.js
  src/component/App.js
  src/component/Form.js
  src/component/MovieInfo.js
  src/component/Movies.js
  src/scss/MovieInfo.scss
  src/scss/Movies.scss
  src/scss/Poster.scss
  src/scss/_extends.scss
Labels: documentation

#29 Cma/feature/final refactor lint
  cypress/cypress.json
  cypress/cypress/fixtures/example.json
  cypress/cypress/integration/examples/actions.spec.js
  cypress/cypress/integration/examples/aliasing.spec.js
  cypress/cypress/integration/examples/assertions.spec.js
  cypress/cypress/integration/examples/connectors.spec.js
  cypress/cypress/integration/examples/cookies.spec.js
  cypress/cypress/integration/examples/cypress_api.spec.js
  cypress/cypress/integration/examples/files.spec.js
  cypress/cypress/integration/examples/local_storage.spec.js
  cypress/cypress/integration/examples/location.spec.js
  cypress/cypress/integration/examples/misc.spec.js
  cypress/cypress/integration/examples/navigation.spec.js
  cypress/cypress/integration/examples/network_requests.spec.js
  cypress/cypress/integration/examples/querying.spec.js
  cypress/cypress/integration/examples/spies_stubs_clocks.spec.js
  cypress/cypress/integration/examples/traversal.spec.js
  cypress/cypress/integration/examples/utilities.spec.js
  cypress/cypress/integration/examples/viewport.spec.js
  cypress/cypress/integration/examples/waiting.spec.js
  cypress/cypress/integration/examples/window.spec.js
  cypress/cypress/plugins/index.js
  cypress/cypress/support/commands.js
  cypress/cypress/support/index.js
  cypress/fixtures/example.json
  cypress/fixtures/profile.json
  cypress/fixtures/users.json
  cypress/integration/cypress.json
  cypress/integration/cypress/fixtures/example.json
  cypress/integration/cypress/plugins/index.js
  cypress/integration/cypress/support/commands.js
  cypress/integration/cypress/support/index.js
  cypress/integration/movie_display.spec.js
  cypress/plugins/index.js
  cypress/screenshots/All Integration Specs/my-image.png
  cypress/support/commands.js
  cypress/support/index.js
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/component/App.js
  src/component/App.test.js
  src/component/Form.js
  src/component/MovieInfo.js
  src/component/Movies.js
  src/component/Poster.js
  src/index.js
  src/logo.svg
  src/scss/MovieInfo.scss
  src/scss/_extends.scss
  src/setupTests.js
Labels: refactor
